### ISSUE TITLE
Wrong code block In behat-loves-mink

### ISSUE THREAD

**Issue by weaverryan** [knpuniversity/behat#37]
On this page: https://knpuniversity.com/screencast/behat/behat-loves-mink#free-behat-steps

The 4th black box (technically, 3rd code block) when we're talking about the default suite, this should be showing `behat.yml`, not `FeatureContext`. Thanks to Dejan for reporting this: https://knpuniversity.com/screencast/behat/behat-loves-mink#comment-2518552378

@bocharsky-bw can you look at this when you have a chance?

**Comment by bocharsky-bw** [comment]
Fixed in https://github.com/knpuniversity/behat/commit/640dfc038c60c6500f5919325a2583e9b6d9265e , rebuilt and published already!

**Comment by weaverryan** [comment]
Dude, so fast - thanks!
